# Generated by Django 5.0.6 on 2024-07-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qyautity',
        ),
        migrations.AddField(
            model_name='cart',
            name='qauntity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
