# Generated by Django 5.0.6 on 2024-06-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Restaurant'), (2, 'Customer')], null=True),
        ),
    ]
