# Generated by Django 5.0.6 on 2024-07-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
