# Generated by Django 5.0.6 on 2024-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_tax',
            new_name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_data',
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('PayPal', 'PayPal'), ('RazorPay', 'RazorPay')], max_length=100),
        ),
    ]
